import { useState } from "react";
import { 
  ArrowLeft, 
  Star, 
  Reply, 
  Forward, 
  Trash2, 
  MoreHorizontal,
  Sparkles,
  Loader2,
  CheckCircle
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { Email } from "@/pages/Inbox";

interface EmailViewProps {
  email: Email | null;
  onBack: () => void;
  onToggleStar: (id: string) => void;
}

export const EmailView = ({ email, onBack, onToggleStar }: EmailViewProps) => {
  const [summary, setSummary] = useState<string | null>(null);
  const [isSummarizing, setIsSummarizing] = useState(false);

  if (!email) {
    return (
      <div className="flex-1 flex items-center justify-center bg-secondary/20">
        <div className="text-center">
          <div className="w-16 h-16 bg-secondary rounded-full flex items-center justify-center mx-auto mb-4">
            <span className="text-2xl">📧</span>
          </div>
          <div className="text-muted-foreground">Select an email to read</div>
        </div>
      </div>
    );
  }

  const handleSummarize = async () => {
    setIsSummarizing(true);
    setSummary(null);
    
    // Simulate AI summarization (would connect to real AI in production)
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    // Generate a contextual summary based on the email
    const summaries: Record<string, string> = {
      "1": "• John Doe confirms purchase of 20M shares at $45.50/share ($910M total)\n• Legal documents needed: transfer agreement, board resolution, SEC Form 4, escrow\n• Action: Confirm receipt, schedule Thursday call",
      "2": "• Q4 roadmap review needed before Friday sync\n• Key dates: Mobile v2.0 (Oct 15), AI features (Nov 1), Enterprise dashboard (Dec 1)\n• Action: Sign-off required by Wednesday EOD",
      "3": "• 5 new LinkedIn connection requests pending\n• Notable: Michael Scott, Jim Halpert from Dunder Mifflin",
      "4": "• Amazon order shipped: AirPods Pro + USB-C cables\n• Delivery: Tomorrow by 9 PM",
      "5": "• Investment Committee meeting Monday 2pm EST\n• Agenda: Q3 review, TechCorp ($15M) & GreenEnergy ($5M) proposals\n• Location: Conference Room A + Zoom",
      "6": "• Dad's surprise 50th birthday party next Saturday 6pm at Uncle Bob's\n• Bring: cake (pickup at Sweet Delights), plates, napkins, guacamole\n• Action: Pick up sister from airport Friday 8:45pm",
      "7": "• PR #234 fixes authentication timeout bug from issue #233\n• Changes: token refresh, retry mechanism, error messages\n• Stats: 4 files, +156/-42 lines",
    };
    
    setSummary(summaries[email.id] || "• Key information extracted from email\n• Action items identified\n• Summary generated by InboxIQ AI");
    setIsSummarizing(false);
  };

  return (
    <div className="flex-1 flex flex-col overflow-hidden bg-background">
      {/* Toolbar */}
      <div className="flex items-center gap-2 p-4 border-b border-border">
        <Button variant="ghost" size="icon" onClick={onBack} className="md:hidden">
          <ArrowLeft className="h-4 w-4" />
        </Button>
        <Button 
          variant="ghost" 
          size="icon"
          onClick={() => onToggleStar(email.id)}
        >
          <Star className={cn(
            "h-4 w-4",
            email.starred ? "fill-yellow-400 text-yellow-400" : ""
          )} />
        </Button>
        <Button variant="ghost" size="icon">
          <Reply className="h-4 w-4" />
        </Button>
        <Button variant="ghost" size="icon">
          <Forward className="h-4 w-4" />
        </Button>
        <Button variant="ghost" size="icon">
          <Trash2 className="h-4 w-4" />
        </Button>
        <Button variant="ghost" size="icon">
          <MoreHorizontal className="h-4 w-4" />
        </Button>
        
        <div className="flex-1" />
        
        {/* AI Summarize Button */}
        <Button 
          onClick={handleSummarize}
          disabled={isSummarizing}
          className="gap-2 bg-gradient-to-r from-primary to-blue-600 hover:from-primary/90 hover:to-blue-600/90"
        >
          {isSummarizing ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <Sparkles className="h-4 w-4" />
          )}
          {isSummarizing ? "Summarizing..." : "AI Summarize"}
        </Button>
      </div>

      {/* AI Summary Card */}
      {(summary || isSummarizing) && (
        <div className="mx-4 mt-4 p-4 bg-primary/5 border border-primary/20 rounded-xl">
          <div className="flex items-center gap-2 mb-3">
            <div className="w-6 h-6 bg-primary/10 rounded-full flex items-center justify-center">
              <Sparkles className="h-3 w-3 text-primary" />
            </div>
            <span className="text-sm font-medium text-primary">AI Summary</span>
            {summary && <CheckCircle className="h-4 w-4 text-green-500 ml-auto" />}
          </div>
          {isSummarizing ? (
            <div className="flex items-center gap-2 text-sm text-muted-foreground">
              <Loader2 className="h-4 w-4 animate-spin" />
              Analyzing email content...
            </div>
          ) : (
            <div className="text-sm text-foreground whitespace-pre-line leading-relaxed">
              {summary}
            </div>
          )}
        </div>
      )}

      {/* Email Content */}
      <div className="flex-1 overflow-y-auto p-6">
        <div className="max-w-3xl">
          <h1 className="text-2xl font-semibold text-foreground mb-4">
            {email.subject}
          </h1>
          
          <div className="flex items-center gap-4 mb-6">
            <div className="w-10 h-10 bg-primary/10 rounded-full flex items-center justify-center">
              <span className="text-primary font-semibold">
                {email.from.charAt(0).toUpperCase()}
              </span>
            </div>
            <div className="flex-1">
              <div className="font-medium text-foreground">{email.from}</div>
              <div className="text-sm text-muted-foreground">{email.fromEmail}</div>
            </div>
            <div className="text-sm text-muted-foreground">{email.date}</div>
          </div>

          <div className="prose prose-sm max-w-none">
            <div className="text-foreground whitespace-pre-line leading-relaxed">
              {email.body}
            </div>
          </div>
        </div>
      </div>

      {/* Reply Box */}
      <div className="p-4 border-t border-border">
        <div className="flex items-center gap-2 p-3 bg-secondary/50 rounded-lg cursor-pointer hover:bg-secondary transition-colors">
          <Reply className="h-4 w-4 text-muted-foreground" />
          <span className="text-sm text-muted-foreground">Click here to reply</span>
        </div>
      </div>
    </div>
  );
};
